<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum DeliveryInformationTransporterCode: string
{
    case POSTNL,_DHL,_DPD,_GLS,_UPS,_OTHER = 'POSTNL, DHL, DPD, GLS, UPS, OTHER';
}
