<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum EconomicOperatorsAddressCountry: string
{
    case AT = 'AT';
    case BE = 'BE';
    case BG = 'BG';
    case HR = 'HR';
    case CY = 'CY';
    case CZ = 'CZ';
    case DK = 'DK';
    case EE = 'EE';
    case FI = 'FI';
    case FR = 'FR';
    case DE = 'DE';
    case GR = 'GR';
    case HU = 'HU';
    case IE = 'IE';
    case IT = 'IT';
    case LV = 'LV';
    case LT = 'LT';
    case LU = 'LU';
    case MT = 'MT';
    case NL = 'NL';
    case PL = 'PL';
    case PT = 'PT';
    case RO = 'RO';
    case SK = 'SK';
    case SI = 'SI';
    case ES = 'ES';
    case SE = 'SE';
    case XI = 'XI';
}
