<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum EconomicOperatorStatus: string
{
    case PENDING = 'PENDING';
    case VALID = 'VALID';
    case INVALID = 'INVALID';
}
