<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetInvoiceRequestsState: string
{
    case OPEN,_UPLOAD_ERROR,_ALL = 'OPEN, UPLOAD_ERROR, ALL';
}
