<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetLoadCarrierLabelsLabelType: string
{
    case WAREHOUSE,_TRANSPORT = 'WAREHOUSE, TRANSPORT';
}
