<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetProductAssetsUsage: string
{
    case PRIMARY,_ADDITIONAL,_IMAGE = 'PRIMARY, ADDITIONAL, IMAGE';
}
