<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetProductCategoriesAcceptLanguage: string
{
    case NL,_NL_BE,_NL_NL,_FR_BE = 'nl, nl-BE, nl-NL, fr-BE';
}
