<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum LoadCarrierTransportState: string
{
    case ANNOUNCED,_PICKED_UP,_UNDERWAY,_DELAYED,_ARRIVED,_ERROR = 'ANNOUNCED, PICKED_UP, UNDERWAY, DELAYED, ARRIVED, ERROR';
}
