<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum NewConditionCategory: string
{
    case NEW = 'NEW';
    case SECONDHAND = 'SECONDHAND';
    case REFURBISHED = 'REFURBISHED';
}
