<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum PickupAppointmentCancellationReason: string
{
    case UNKNOWN_ADDRESS,_NOT_READY,_NO_LABEL,_WRONG_PACKAGE,_NOT_AT_HOME,_OTHER_REASON,_REQUEST_FROM_RETAILER = 'UNKNOWN_ADDRESS, NOT_READY, NO_LABEL, WRONG_PACKAGE, NOT_AT_HOME, OTHER_REASON, REQUEST_FROM_RETAILER';
}
