<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum PolicyViolationViolationType: string
{
    case POINTS_ADDITION = 'POINTS_ADDITION';
    case POINTS_DEDUCTION = 'POINTS_DEDUCTION';
    case WARNING = 'WARNING';
}
