<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ProductLabelsRequestLabelFormat: string
{
    case AVERY_J8159,_AVERY_J8160,_AVERY_3474,_DYMO_99012,_BROTHER_DK11208D,_ZEBRA_Z_PERFORM_1000T = 'AVERY_J8159, AVERY_J8160, AVERY_3474, DYMO_99012, BROTHER_DK11208D, ZEBRA_Z_PERFORM_1000T';
}
