<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum QualityKpiScoreAggregationLevel: string
{
    case RETAILER = 'RETAILER';
    case PROPOSITION = 'PROPOSITION';
}
