<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ReasonCategory: string
{
    case CONTENT = 'CONTENT';
    case PRICE = 'PRICE';
    case STOCK = 'STOCK';
    case SHOP_STATUS = 'SHOP_STATUS';
    case SELLING_RIGHTS = 'SELLING_RIGHTS';
    case ACCOUNT_RIGHTS = 'ACCOUNT_RIGHTS';
    case ON_HOLD = 'ON_HOLD';
    case ASSORTMENT_POLICY = 'ASSORTMENT_POLICY';
    case OFFER = 'OFFER';
}
