<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum RefurbishedConditionGrade: string
{
    case A = 'A';
    case B = 'B';
    case C = 'C';
}
