<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ReplenishmentLineLineState: string
{
    case ANNOUNCED,_UNANNOUNCED,_UNKNOWN = 'ANNOUNCED, UNANNOUNCED, UNKNOWN';
}
