<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ReplenishmentResponseState: string
{
    case ANNOUNCED,_IN_TRANSIT,_ARRIVED_AT_WH,_IN_PROGRESS_AT_WH,_CANCELLED,_DONE = 'ANNOUNCED, IN_TRANSIT, ARRIVED_AT_WH, IN_PROGRESS_AT_WH, CANCELLED, DONE';
}
