<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum RetailerRatingsRatingMethod: string
{
    case ALL_REVIEWS = 'ALL_REVIEWS';
    case RECENT_REVIEWS = 'RECENT_REVIEWS';
}
