<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum RetailerKpiScoresKpi: string
{
    case CANCELLATIONS = 'CANCELLATIONS';
    case CASE_ITEM_RATIO = 'CASE_ITEM_RATIO';
    case FULFILMENT = 'FULFILMENT';
    case HANDOVER = 'HANDOVER';
    case ON_TIME = 'ON_TIME';
    case RESPONSE_TIME = 'RESPONSE_TIME';
    case RETURNS = 'RETURNS';
    case REVIEWS = 'REVIEWS';
    case TRACK_AND_TRACE = 'TRACK_AND_TRACE';
}
