<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ShippingMethodScoreShippingMethod: string
{
    case SHIPPING_VIA_BOL = 'SHIPPING_VIA_BOL';
    case LOGISTICS_VIA_BOL = 'LOGISTICS_VIA_BOL';
    case OWN_SHIPPING = 'OWN_SHIPPING';
}
