<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ShipmentDetailsLanguage: string
{
    case NL,_NL_BE,_FR,_FR_BE = 'nl, nl-BE, fr, fr-BE';
}
