<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum V11FulfilmentSchedule: string
{
    case BOL_DELIVERY_PROMISE = 'BOL_DELIVERY_PROMISE';
    case MY_DELIVERY_PROMISE = 'MY_DELIVERY_PROMISE';
    case SHIPPING_VIA_BOL = 'SHIPPING_VIA_BOL';
}
