<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class CreateEconomicOperator extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'externalReference' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'name' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'address' => [ 'model' => EconomicOperatorsAddress::class, 'enum' => null, 'array' => false ],
            'contactInformation' => [ 'model' => ContactInformation::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The reference for economic operator as it is known by the retailer.
     */
    public $externalReference;

    /**
     * @var string Represents the legal name of the economic operator.
     */
    public $name;

    /**
     * @var EconomicOperatorsAddress Specifies the full legal address, including street, house number, postal code,
     * city, and country.
     */
    public $address;

    /**
     * @var ContactInformation
     */
    public $contactInformation;
}
