<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class CreateCountryAvailability extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'countryCode' => [ 'model' => null, 'enum' => Enum\CreateCountryAvailabilityCountryCode::class, 'array' => false ],
        ];
    }

    /**
     * @var Enum\CreateCountryAvailabilityCountryCode The country that applies to the offer.
     */
    public $countryCode;
}
