<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class EconomicOperatorsAddress extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'street' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'houseNumber' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'additionalAddressInfo' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'postalCode' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'city' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'country' => [ 'model' => null, 'enum' => Enum\EconomicOperatorsAddressCountry::class, 'array' => false ],
        ];
    }

    /**
     * @var string The street name of the address.
     */
    public $street;

    /**
     * @var string The house number, which may include extensions like 'A' or 'B'.
     */
    public $houseNumber;

    /**
     * @var string Optional additional information about the address (e.g., floor number, apartment number).
     */
    public $additionalAddressInfo;

    /**
     * @var string The postal code of the address, following the country's postal code format.
     */
    public $postalCode;

    /**
     * @var string The city where the address is located.
     */
    public $city;

    /**
     * @var Enum\EconomicOperatorsAddressCountry Specifies the country within the European Union where the economic
     * operator is located. Only supported EU countries are allowed.
     */
    public $country;
}
