<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class EconomicOperatorsPage extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'operators' => [ 'model' => EconomicOperator::class, 'enum' => null, 'array' => true ],
            'page' => [ 'model' => Page::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var EconomicOperator[] List of economic operators on the current page.
     */
    public $operators = [];

    /**
     * @var Page
     */
    public $page;
}
