<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class KpiScore extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'kpi' => [ 'model' => null, 'enum' => Enum\KpiScoreKpi::class, 'array' => false ],
            'score' => [ 'model' => V11Score::class, 'enum' => null, 'array' => false ],
            'norm' => [ 'model' => V11Norm::class, 'enum' => null, 'array' => false ],
            'period' => [ 'model' => Period::class, 'enum' => null, 'array' => false ],
            'excluded' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\KpiScoreKpi Name of the service norm.
     */
    public $kpi;

    /**
     * @var V11Score The score of the service norm.
     */
    public $score;

    /**
     * @var V11Norm Represents the norm of the KPI.
     */
    public $norm;

    /**
     * @var Period Period for which the score was calculated.
     */
    public $period;

    /**
     * @var bool Flag to represent whether the KPI is excluded from strike calculation or not.
     */
    public $excluded;
}
