<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class OfferResponse extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'offerId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'ean' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'lastModifiedDateTime' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'reference' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'onHoldByRetailer' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'economicOperatorId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'unknownProductTitle' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'stock' => [ 'model' => V11Stock::class, 'enum' => null, 'array' => false ],
            'countryAvailabilities' => [ 'model' => CountryAvailability::class, 'enum' => null, 'array' => true ],
            'condition' => [ 'model' => V11Condition::class, 'enum' => null, 'array' => false ],
            'product' => [ 'model' => V11Product::class, 'enum' => null, 'array' => false ],
            'pricing' => [ 'model' => V11Pricing::class, 'enum' => null, 'array' => false ],
            'fulfilment' => [ 'model' => V11Fulfilment::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string A globally unique identifier assigned to each offer, used for tracking and referencing within the
     * system.
     */
    public $offerId;

    /**
     * @var string The European Article Number (EAN) uniquely identifying the product, used for inventory and cataloging
     * purposes. Note that in case an ISBN is provided, it will be replaced with the actual EAN belonging to this ISBN.
     */
    public $ean;

    /**
     * @var string The date time this offer was last modified by either bol or the partner itself.
     */
    public $lastModifiedDateTime;

    /**
     * @var string A custom reference string defined by the retailer to help identify and correlate the offer with
     * internal systems.
     */
    public $reference;

    /**
     * @var bool Specifies whether the offer should be listed for sale on bol. Useful for temporarily suspending
     * visibility without deletion.
     */
    public $onHoldByRetailer;

    /**
     * @var string An identifier referring to the Economic operator entity (manufacturer, authorized party, importer,
     * distributor or other natural person or legal entity for whom the obligations apply with regards to the
     * manufacturing, or making available on the market of the product in line with the applicable EU laws.
     */
    public $economicOperatorId;

    /**
     * @var string If the product is not recognized by bol, the retailer may use this field to provide a custom title
     * for identification. Note that, in case the product is known to bol, the unknown product title will not be stored.
     */
    public $unknownProductTitle;

    /**
     * @var V11Stock
     */
    public $stock;

    /**
     * @var CountryAvailability[]
     */
    public $countryAvailabilities = [];

    /**
     * @var V11Condition Describes the physical and functional state of the product, such as new, secondhand, or
     * refurbished.
     */
    public $condition;

    /**
     * @var V11Product
     */
    public $product;

    /**
     * @var V11Pricing
     */
    public $pricing;

    /**
     * @var V11Fulfilment The fulfilment method. Fulfilled by the retailer (FBR) or fulfilled by bol (FBB)
     */
    public $fulfilment;

    public function getLastModifiedDateTime(): ?\DateTime
    {
        if (empty($this->lastModifiedDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->lastModifiedDateTime);
    }

    /**
     * Returns bolProductId from product.
     * @return string BolProductId from product.
     */
    public function getBolProductId(): string
    {
        return $this->product->bolProductId;
    }

    /**
     * Sets product by bolProductId.
     * @param string $bolProductId BolProductId for product.
     */
    public function setBolProductId(string $bolProductId): void
    {
        $this->product = V11Product::constructFromArray(['bolProductId' => $bolProductId]);
    }
}
