<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class Page extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'pageSize' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'pageNumber' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'numberOfPages' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'totalCount' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int Number of items per page, with a maximum limit of 100
     */
    public $pageSize;

    /**
     * @var int The current page number (1-indexed)
     */
    public $pageNumber;

    /**
     * @var int Total number of pages available
     */
    public $numberOfPages;

    /**
     * @var int Total count of all items
     */
    public $totalCount;
}
