<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class PatchOfferRequest extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'unknownProductTitle' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'economicOperatorId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'onHoldByRetailer' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'reference' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'countryAvailabilities' => [ 'model' => CreateCountryAvailability::class, 'enum' => null, 'array' => true ],
            'pricing' => [ 'model' => V11Pricing::class, 'enum' => null, 'array' => false ],
            'fulfilment' => [ 'model' => V11Fulfilment::class, 'enum' => null, 'array' => false ],
            'stock' => [ 'model' => UpdateStock::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string If the product is not recognized by bol, the retailer may use this field to provide a custom title
     * for identification. Note that, in case the product is known to bol, the unknown product title will not be stored.
     */
    public $unknownProductTitle;

    /**
     * @var string An identifier referring to the Economic operator entity (manufacturer, authorized party, importer,
     * distributor or other natural person or legal entity for whom the obligations apply with regards to the
     * manufacturing, or making available on the market of the product in line with the applicable EU laws.
     */
    public $economicOperatorId;

    /**
     * @var bool Specifies whether the offer should be listed for sale on bol. Useful for temporarily suspending
     * visibility without deletion.
     */
    public $onHoldByRetailer;

    /**
     * @var string A custom reference string defined by the retailer to help identify and correlate the offer with
     * internal systems.
     */
    public $reference;

    /**
     * @var CreateCountryAvailability[]
     */
    public $countryAvailabilities = [];

    /**
     * @var V11Pricing
     */
    public $pricing;

    /**
     * @var V11Fulfilment The fulfilment method. Fulfilled by the retailer (FBR) or fulfilled by bol (FBB)
     */
    public $fulfilment;

    /**
     * @var UpdateStock
     */
    public $stock;

    /**
     * Returns an array with the countryCodes from countryAvailabilities.
     * @return string[] CountryCodes from countryAvailabilities.
     */
    public function getCountryAvailabilitiesCountryCodes(): array
    {
        return array_map(function ($model) {
            return $model->countryCode;
        }, $this->countryAvailabilities);
    }

    /**
     * Sets countryAvailabilities by an array of countryCodes.
     * @param string[] $countryCodes CountryCodes for countryAvailabilities.
     */
    public function setCountryAvailabilitiesCountryCodes(array $countryCodes): void
    {
        $this->countryAvailabilities = array_map(function ($countryCode) {
            return CreateCountryAvailability::constructFromArray(['countryCode' => $countryCode]);
        }, $countryCodes);
    }

    /**
     * Adds a new CreateCountryAvailability to countryAvailabilities by countryCode.
     * @param string $countryCode CountryCode for the CreateCountryAvailability to add.
     */
    public function addCountryAvailabilitiesCountryCode(string $countryCode): void
    {
        $this->countryAvailabilities[] = CreateCountryAvailability::constructFromArray(['countryCode' => $countryCode]);
    }
}
