<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class PerformanceStatus extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'monitoringSystem' => [ 'model' => MonitoringSystem::class, 'enum' => null, 'array' => false ],
            'policy' => [ 'model' => Policy::class, 'enum' => null, 'array' => false ],
            'qualityScore' => [ 'model' => QualityScore::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var MonitoringSystem Represents retailer's current monitoring system name and strike information.
     */
    public $monitoringSystem;

    /**
     * @var Policy Represents policy violation overview.
     */
    public $policy;

    /**
     * @var QualityScore Represents the retailer's quality score and performance evaluation for the applied period,
     * including the overall score and breakdowns across shipping methods.
     */
    public $qualityScore;
}
