<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class Period extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'id' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'type' => [ 'model' => null, 'enum' => Enum\PeriodType::class, 'array' => false ],
        ];
    }

    /**
     * @var string Week in the format YYYY-WW (ISO-8601).
     */
    public $id;

    /**
     * @var Enum\PeriodType Period type for the score. Currently can only be "week".
     */
    public $type;
}
