<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class PolicyViolation extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'violationId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'registrationDateTime' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'category' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'subCategory' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'violationType' => [ 'model' => null, 'enum' => Enum\PolicyViolationViolationType::class, 'array' => false ],
            'points' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'isProportionalityApplied' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'preProportionalPoints' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The unique identifier of a policy violation.
     */
    public $violationId;

    /**
     * @var string A timestamp combining both date and time, represented in ISO 8601 format (e.g.,
     * YYYY-MM-DDTHH:mm:ssZ). Includes timezone information.
     */
    public $registrationDateTime;

    /**
     * @var string Policy violated category name.
     */
    public $category;

    /**
     * @var string Policy violated sub-category name.
     */
    public $subCategory;

    /**
     * @var Enum\PolicyViolationViolationType Type of the policy violation.
     */
    public $violationType;

    /**
     * @var int The number of points assigned to the policy violation.
     */
    public $points;

    /**
     * @var bool Has the number of points deducted been lowered because of proportionality to offer and order count.
     */
    public $isProportionalityApplied;

    /**
     * @var int The number of points that would have been deducted without proportionality correction, as indicated by
     * isProportionalityApplied.
     */
    public $preProportionalPoints;

    public function getRegistrationDateTime(): ?\DateTime
    {
        if (empty($this->registrationDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->registrationDateTime);
    }
}
