<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class Profile extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'profileId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'name' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'isDefault' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'workingDays' => [ 'model' => WorkingDay::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string Unique identifier of the delivery promise profile
     */
    public $profileId;

    /**
     * @var string Human-readable name of the profile
     */
    public $name;

    /**
     * @var bool Indicates whether this profile is the default
     */
    public $isDefault;

    /**
     * @var WorkingDay[] List of working days
     */
    public $workingDays = [];
}
