<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class QualityScore extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'yearWeek' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'score' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'shippingMethodScores' => [ 'model' => ShippingMethodScore::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string The period a quality score applies to in the format YYYY-WW (ISO-8601).
     */
    public $yearWeek;

    /**
     * @var int The quality score. A retailer's top-level outcome for a given period in a score from 0–100.
     */
    public $score;

    /**
     * @var ShippingMethodScore[]
     */
    public $shippingMethodScores = [];
}
