<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class QualityKpiScore extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'kpiName' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'score' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'norm' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'aggregationLevel' => [ 'model' => null, 'enum' => Enum\QualityKpiScoreAggregationLevel::class, 'array' => false ],
        ];
    }

    /**
     * @var string Name of the KPI.
     */
    public $kpiName;

    /**
     * @var float The calculated score of the KPI.
     */
    public $score;

    /**
     * @var float The threshold a KPI value must meet to be considered conforming.
     */
    public $norm;

    /**
     * @var Enum\QualityKpiScoreAggregationLevel The level at which the KPI data is aggregated (RETAILER or PROPOSITION)
     */
    public $aggregationLevel;
}
