<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class Reason extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'category' => [ 'model' => null, 'enum' => Enum\ReasonCategory::class, 'array' => false ],
            'code' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'description' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'missingAttributes' => [ 'model' => MissingAttribute::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var Enum\ReasonCategory
     */
    public $category;

    /**
     * @var string Unique reason code
     */
    public $code;

    /**
     * @var string A description explaining the reason why this offer is marked as offline.
     */
    public $description;

    /**
     * @var MissingAttribute[]
     */
    public $missingAttributes = [];

    /**
     * Returns an array with the names from missingAttributes.
     * @return string[] Names from missingAttributes.
     */
    public function getMissingAttributesNames(): array
    {
        return array_map(function ($model) {
            return $model->name;
        }, $this->missingAttributes);
    }

    /**
     * Sets missingAttributes by an array of names.
     * @param string[] $names Names for missingAttributes.
     */
    public function setMissingAttributesNames(array $names): void
    {
        $this->missingAttributes = array_map(function ($name) {
            return MissingAttribute::constructFromArray(['name' => $name]);
        }, $names);
    }

    /**
     * Adds a new MissingAttribute to missingAttributes by name.
     * @param string $name Name for the MissingAttribute to add.
     */
    public function addMissingAttributesName(string $name): void
    {
        $this->missingAttributes[] = MissingAttribute::constructFromArray(['name' => $name]);
    }
}
