<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class RefurbishedCondition extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'category' => [ 'model' => null, 'enum' => Enum\RefurbishedConditionCategory::class, 'array' => false ],
            'grade' => [ 'model' => null, 'enum' => Enum\RefurbishedConditionGrade::class, 'array' => false ],
            'margin' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\RefurbishedConditionCategory
     */
    public $category;

    /**
     * @var Enum\RefurbishedConditionGrade
     */
    public $grade;

    /**
     * @var bool Indicates if there is a margin adjustment due to the condition.
     */
    public $margin;
}
