<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class RetailerInformation extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'retailerId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'displayName' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'companyName' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'vatNumber' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'kvkNumber' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'registrationDateTime' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'countryAvailability' => [ 'model' => null, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string Represents the retailer who owns the economic operator.
     */
    public $retailerId;

    /**
     * @var string The shop name of the retailer.
     */
    public $displayName;

    /**
     * @var string The official name of the company as registered with the relevant authorities. This name is used for
     * identification and legal purposes.
     */
    public $companyName;

    /**
     * @var string A unique identifier for the company's value-added tax (VAT) registration. This number is used for tax
     * reporting purposes within the European Union. It typically includes a country code followed by alphanumeric
     * characters.
     */
    public $vatNumber;

    /**
     * @var string The unique registration number assigned to a company by the Dutch Chamber of Commerce (Kamer van
     * Koophandel - KVK). This number is required for conducting business in the Netherlands.
     */
    public $kvkNumber;

    /**
     * @var string A timestamp combining both date and time, represented in ISO 8601 format (e.g.,
     * YYYY-MM-DDTHH:mm:ssZ). Includes timezone information.
     */
    public $registrationDateTime;

    /**
     * @var array
     */
    public $countryAvailability = [];

    public function getRegistrationDateTime(): ?\DateTime
    {
        if (empty($this->registrationDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->registrationDateTime);
    }
}
