<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class RetailerRatings extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'ratingMethod' => [ 'model' => null, 'enum' => Enum\RetailerRatingsRatingMethod::class, 'array' => false ],
            'retailerRating' => [ 'model' => V11RetailerRating::class, 'enum' => null, 'array' => false ],
            'retailerReview' => [ 'model' => V11RetailerReview::class, 'enum' => null, 'array' => false ],
            'isTopRetailer' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\RetailerRatingsRatingMethod An identifier that identifies if the rating is calculated over the past
     * three months or on all reviews for the retailer.
     */
    public $ratingMethod;

    /**
     * @var V11RetailerRating Represents rating on retailer, product, delivery time, shipping and service level.
     */
    public $retailerRating;

    /**
     * @var V11RetailerReview Represents positive, negative, neutral and total review count.
     */
    public $retailerReview;

    /**
     * @var bool Retailer flag if top seller or not.
     */
    public $isTopRetailer;
}
