<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class SecondhandCondition extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'category' => [ 'model' => null, 'enum' => Enum\SecondhandConditionCategory::class, 'array' => false ],
            'state' => [ 'model' => null, 'enum' => Enum\SecondhandConditionState::class, 'array' => false ],
            'comment' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\SecondhandConditionCategory
     */
    public $category;

    /**
     * @var Enum\SecondhandConditionState
     */
    public $state;

    /**
     * @var string The description of the condition of the product. Only allowed if name is not NEW and may not contain
     * e-mail addresses.
     */
    public $comment;
}
