<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ShippingMethodScore extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'shippingMethod' => [ 'model' => null, 'enum' => Enum\ShippingMethodScoreShippingMethod::class, 'array' => false ],
            'score' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'weight' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'kpiScores' => [ 'model' => QualityKpiScore::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var Enum\ShippingMethodScoreShippingMethod The logistical method used to fulfill and ship the item: *
     * `SHIPPING_VIA_BOL` - Shipping by bol (Dutch: Vvb - Verzenden via bol) * `LOGISTICS_VIA_BOL` - Fulfilment by bol
     * (FBB) (Dutch: Lvb - Logistiek via bol) * `OWN_SHIPPING` - Fulfilment by retailer (FBR) (Dutch: Eigen
     * verzendwijze)
     */
    public $shippingMethod;

    /**
     * @var int The calculated quality score for this shipping method.
     */
    public $score;

    /**
     * @var float The weight assigned to this fulfilment type's score in the overall quality score calculation.
     */
    public $weight;

    /**
     * @var QualityKpiScore[]
     */
    public $kpiScores = [];
}
