<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class StockReason extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'category' => [ 'model' => null, 'enum' => Enum\StockReasonCategory::class, 'array' => false ],
            'code' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'description' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\StockReasonCategory
     */
    public $category;

    /**
     * @var string Unique reason code
     */
    public $code;

    /**
     * @var string A description explaining the reason why this offer is marked as offline.
     */
    public $description;
}
