<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class StrikeWeekReason extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'week' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'reasons' => [ 'model' => null, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string Strike week in the format YYYY-WW (ISO-8601).
     */
    public $week;

    /**
     * @var array
     */
    public $reasons = [];
}
