<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class Strike extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'count' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'weeks' => [ 'model' => StrikeWeekReason::class, 'enum' => null, 'array' => true ],
            'monitorPeriod' => [ 'model' => MonitorPeriod::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int The number of strikes in the current monitoring weeks.
     */
    public $count;

    /**
     * @var StrikeWeekReason[]
     */
    public $weeks = [];

    /**
     * @var MonitorPeriod Represents start and end week of the monitoring period. Currently 22 weeks.
     */
    public $monitorPeriod;
}
