<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11Condition extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'category' => [ 'model' => null, 'enum' => Enum\V11ConditionCategory::class, 'array' => false ],
            'state' => [ 'model' => null, 'enum' => Enum\V11ConditionState::class, 'array' => false ],
            'comment' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'grade' => [ 'model' => null, 'enum' => Enum\V11ConditionGrade::class, 'array' => false ],
            'margin' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\V11ConditionCategory
     */
    public $category;

    /**
     * @var Enum\V11ConditionState
     */
    public $state;

    /**
     * @var string The description of the condition of the product. Only allowed if name is not NEW and may not contain
     * e-mail addresses.
     */
    public $comment;

    /**
     * @var Enum\V11ConditionGrade
     */
    public $grade;

    /**
     * @var bool Indicates if there is a margin adjustment due to the condition.
     */
    public $margin;
}
