<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11Fulfilment extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'method' => [ 'model' => null, 'enum' => Enum\V11FulfilmentMethod::class, 'array' => false ],
            'schedule' => [ 'model' => null, 'enum' => Enum\V11FulfilmentSchedule::class, 'array' => false ],
            'profileId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'deliveryPromise' => [ 'model' => V11FulfilmentDeliveryPromise::class, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\V11FulfilmentMethod
     */
    public $method;

    /**
     * @var Enum\V11FulfilmentSchedule
     */
    public $schedule;

    /**
     * @var string The identifier of the delivery promise profile.
     */
    public $profileId;

    /**
     * @var V11FulfilmentDeliveryPromise Specifies the expected delivery timeframe for the offer. This value will only
     * be used in combination with fulfilmentMethod 'FBR'.
     */
    public $deliveryPromise;
}
