<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11FulfilmentDeliveryPromise extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'minimumDaysToCustomer' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'maximumDaysToCustomer' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'ultimateOrderTime' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int The minimum amount of days it takes to deliver this item to the customer.
     */
    public $minimumDaysToCustomer;

    /**
     * @var int The maximum amount of days it takes to deliver this item to the customer.
     */
    public $maximumDaysToCustomer;

    /**
     * @var string The ultimate order time the customer needs to place an order on the bol marketplace for next day
     * delivery. If the order is placed after this time, the delivery promise will include one additional day.
     */
    public $ultimateOrderTime;
}
