<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11Norm extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'type' => [ 'model' => null, 'enum' => Enum\V11NormType::class, 'array' => false ],
            'condition' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'value' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\V11NormType Norm type used for the service norm.
     */
    public $type;

    /**
     * @var string Logical operator used for the norm and score.
     */
    public $condition;

    /**
     * @var float Actual norm used for the service norm.
     */
    public $value;
}
