<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11PricingBundlePrice extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'quantity' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'unitPrice' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int The minimum quantity a customer must order in order to receive a discount. The array must contain at
     * least one element with a value of 1. If multiple values are provided, they must be in strictly increasing order.
     */
    public $quantity;

    /**
     * @var float The unit price including VAT, applicable when the customer orders at least the corresponding minimum
     * quantity. If multiple prices are provided, they must be listed in strictly decreasing order, matching the
     * increasing order of the associated quantity thresholds.
     */
    public $unitPrice;
}
