<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11RetailerRating extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'retailerRating' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'productInformationRating' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'deliveryTimeRating' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'shippingRating' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'serviceRating' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var float Retailer general rating.
     */
    public $retailerRating;

    /**
     * @var float Retailer product rating.
     */
    public $productInformationRating;

    /**
     * @var float Retailer delivery time rating.
     */
    public $deliveryTimeRating;

    /**
     * @var float Retailer shipping rating.
     */
    public $shippingRating;

    /**
     * @var float Retailer service rating.
     */
    public $serviceRating;
}
