<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11Score extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'numerator' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'denominator' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'value' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'distanceToNorm' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'conformsToNorm' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int The numerator of the score.
     */
    public $numerator;

    /**
     * @var int The denominator of the score.
     */
    public $denominator;

    /**
     * @var float The value of the score.
     */
    public $value;

    /**
     * @var float Value representing distance between score and the norm.
     */
    public $distanceToNorm;

    /**
     * @var bool A flag which says whether score conforms to the norm or not.
     */
    public $conformsToNorm;
}
