<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class V11Stock extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'amount' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'correctedStock' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'managedByRetailer' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int The amount of stock available for the specified product present in the retailers warehouse. Note that
     * this should not be the FBB stock.
     */
    public $amount;

    /**
     * @var int The available stock after accounting for open and processed orders, based on retailer provided inventory
     * data. Once this value reaches zero the offer becomes unavailable for sale on the web shop.
     */
    public $correctedStock;

    /**
     * @var bool Determines if stock levels are manually managed by the retailer or automatically adjusted based on open
     * orders.
     */
    public $managedByRetailer;
}
