<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class WorkingDay extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'dayOfWeek' => [ 'model' => null, 'enum' => Enum\WorkingDayDayOfWeek::class, 'array' => false ],
            'isDeliveryDay' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'latestOrderTime' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'minCarrierDeliveryDays' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'maxCarrierDeliveryDays' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\WorkingDayDayOfWeek The day of the week
     */
    public $dayOfWeek;

    /**
     * @var bool Indicates whether the carrier is delivering orders to the customer on this day
     */
    public $isDeliveryDay;

    /**
     * @var string The daily cut-off time (format HH:mm) for handing orders over to the carrier. Orders placed before
     * the cut-off time are expected to be handed over the same day; orders placed after the cut-off are handed over on
     * the next eligible handover day. If null, the day is considered to be a non-handover day.
     */
    public $latestOrderTime;

    /**
     * @var int The minimum number of days for the carrier to deliver the package. Defaults to 1.
     */
    public $minCarrierDeliveryDays;

    /**
     * @var int The maximum number of days for the carrier to deliver the package. Defaults to 1.
     */
    public $maxCarrierDeliveryDays;
}
